apiVersion: v1 #it is version of your kubernetes api
kind: Pod
metadata:
  name: nginx
  #namespace: myapp
  labels:
    run: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: my-pv
          mountPath: "/usr/share/nginx/html"
  volumes:
    - name: my-pv
      persistentVolumeClaim:
        claimName: pvc-nginx