apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: lets-encrypt-prod-issuer
  namespace: grafana
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "zuhrasalieva@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: grafana
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: grafana-tls
  namespace: grafana
spec:
  secretName: grafana-tls
  issuerRef:
    name: lets-encrypt-prod-issuer
    kind: Issuer
  commonName: grafana.zukhrasalieva.com
  dnsNames:
    - grafana.zukhrasalieva.com